### ISSUE TITLE
Remove index.ts

### ISSUE THREAD

**Issue by pyphilia** [graasp/graasp-sdk#390]
When possible I think we should try to import from the files directly and not from the indexes. re-exporting indexes is actually not a very good practice, as it adds layers of indirection.

_Originally posted by @spaenleh in https://github.com/graasp/graasp-sdk/pull/389#discussion_r1469131759_

**Comment by spaenleh** [comment]
During the migration to ESM, intermediary index were removed in favor for direct exports to the main index.ts file reducing tbe number of indirections
